#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.f1cb863347dd3555159f014fccd055b32a256427.name = "Last packaging v1 version"
