#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_script_progression --message="Restoring the app main directory..."

# ynh_restore_file --origin_path="$install_dir"
ynh_restore "$install_dir"

# Restore permissions on app files
chown -R $app:www-data "$install_dir"

setfacl -m g:$app:r-x "$install_dir"
setfacl -m g:www-data:r-x "$install_dir"
chmod -R 755 "$install_dir"

# don't allow read access to config.php and pages/ for everyone
chmod 750 "$install_dir"/config.php
chmod -R 750 "$install_dir"/var/pages/ 

# chmod root folder
chmod 750 "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

#ynh_restore --origin_path="/etc/php/$php_version/fpm/pool.d/$app.conf"
ynh_restore --origin_path="/etc/php/${phpversion}/fpm/pool.d/$app.conf"

ynh_restore --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression --message="Reloading NGINX web server and PHP-FPM..."

#ynh_systemctl --service="php$php_version-fpm" --action=reload
#ynh_systemctl --service=nginx --action=reload

ynh_systemd_action --service_name=php${phpversion}-fpm --action=reload
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
